{
  “name”: “Untitled GraphQL Schema”,
  “schemaPath”: “schema.sdl”,
  “extensions”: {
    “endpoints”: {
      “Default GraphQL Endpoint”: {
        “url”: “https://vmeapi.demo.brainvire.dev/graphql",
        “headers”: {
          “user-agent”: “JS GraphQL”
        },
        “introspect”: false
      }
    }
  }
}